title: KR Game Studios
description: Making Games on a Shoestring Budget!
logo: logo_400x400.png
author: Kayne Ruse (Ratstail91)

timezone: Australia/Sydney
remote_theme: pages-themes/minimal@v0.2.0
excerpt_separator: <!--more-->
#show_drafts: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:collection/:name
  unlisted:
    output: true
    permalink: /:collection/:name

plugins:
- jekyll-remote-theme
- jekyll-seo-tag

