title: KR Game Studios
description: Making Games on a Shoestring Budget!
logo: logo_400x400.png
author: Kayne Ruse (Ratstail91)

timezone: Australia/Sydney
excerpt_separator: <!--more-->
#show_drafts: true

collections:
  posts:
    output: true
    permalink: /:name
  unlisted:
    output: true
    permalink: /:name

plugins:
- jekyll-seo-tag

